# -*- coding: utf-8 -*-
"""python 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12EhTnXPFvZ_BYYtAHwQEwKiHYK2ahbzO

1.The provided code stub reads two integers from STDIN,  and . Add code to print three lines where:

The first line contains the sum of the two numbers.
The second line contains the difference of the two numbers (first - second).
The third line contains the product of the two numbers.
"""

a=int(input())
b=int(input())
print(a+b)
print(a-b)
print(a*b)

